### PR TITLE
GROW-979 SF

### PR DESCRIPTION
**Pull request by istvansajtos**
[GROW-979](https://issues.liferay.com/browse/GROW-979)

Hi,

This is just an additional syntax update commit to fix a deployment failure.

Thanks,
Pisti

### CODE REVIEW

**Comment by balcsida** [comment]
Hi @istvansajtos,

I'm still getting the following error:

```
liferay_1    | org.osgi.framework.BundleException: Could not resolve module: com.liferay.grow.social.activity.customizer.activities.query.helper [1118]_  Unresolved requirement: Import-Package: com.liferay.social.activities.web.internal.util; version="[1.0.0,2.0.0)"_    -> Export-Package: com.liferay.social.activities.web.internal.util; bundle-symbolic-name="com.liferay.grow.social.activity.customizer.social.activities.web.fragment"; bundle-version="1.0.0"; version="1.0.0"_       com.liferay.grow.social.activity.customizer.social.activities.web.fragment [1126]_         Unresolved requirement: Fragment-Host: com.liferay.social.activities.web; bundle-version="[4.0.0,5.0.0)"_         Unresolved requirement: Import-Package: com.liferay.social.activity.customizer.query.helper_           -> Export-Package: com.liferay.social.activity.customizer.query.helper; bundle-symbolic-name="com.liferay.grow.social.activity.customizer.activities.query.helper"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.liferay.portal.kernel.model,com.liferay.portal.kernel.service,com.liferay.social.activities.web.internal.util,com.liferay.social.activity.customizer.service,com.liferay.social.kernel.model,com.liferay.social.kernel.service"_ [Sanitized]
liferay_1    |         at org.eclipse.osgi.container.Module.start(Module.java:444)
liferay_1    |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
liferay_1    |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
liferay_1    |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
liferay_1    |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
liferay_1    |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
liferay_1    |         at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
liferay_1    |         at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
liferay_1    | [dxp] ERROR [main][LogService:93] Error while starting bundle: file:/opt/liferay/osgi/modules/com.liferay.grow.social.activity.customizer.activities.query.helper.jar
liferay_1    | org.osgi.framework.BundleException: Could not resolve module: com.liferay.grow.social.activity.customizer.activities.query.helper [1118]_  Unresolved requirement: Import-Package: com.liferay.social.activities.web.internal.util; version="[1.0.0,2.0.0)"_    -> Export-Package: com.liferay.social.activities.web.internal.util; bundle-symbolic-name="com.liferay.grow.social.activity.customizer.social.activities.web.fragment"; bundle-version="1.0.0"; version="1.0.0"_       com.liferay.grow.social.activity.customizer.social.activities.web.fragment [1126]_         Unresolved requirement: Fragment-Host: com.liferay.social.activities.web; bundle-version="[4.0.0,5.0.0)"_         Unresolved requirement: Import-Package: com.liferay.social.activity.customizer.query.helper_           -> Export-Package: com.liferay.social.activity.customizer.query.helper; bundle-symbolic-name="com.liferay.grow.social.activity.customizer.activities.query.helper"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.liferay.portal.kernel.model,com.liferay.portal.kernel.service,com.liferay.social.activities.web.internal.util,com.liferay.social.activity.customizer.service,com.liferay.social.kernel.model,com.liferay.social.kernel.service"_ [Sanitized]
```

Could you please check it again?

Kind regards,
@balcsida

**Comment by istvansajtos** [comment]
Hi @balcsida ,

I could also reproduce the deployment issue. My observation is that it occurs only after a clean restart (when osgi/state is deleted before starting the server).

In my opinion, the issue is related to https://issues.liferay.com/browse/LPS-102027, but I'm not 100% sure. I will test it.

Can we avoid deleting osgi/state before server startups?

Thank you,
Pisti

**Comment by balcsida** [comment]
Hi @istvansajtos,

Unfortunately, it is not possible by design.

During every startup, Kubernetes creates a brand new instance of the service (in this case, Liferay), therefore, everything that is not persisted in the container is lost.
In theory, we could persist `osgi/state` folder, but that would cause unstable and unpredictable behavior because that folder would be literally converted to an NFS share - and eventually the increased latency would cause something bad.

Kind regards,
Dávid

**Comment by istvansajtos** [comment]
Hi @balcsida 

What you wrote [here](https://liferay.slack.com/archives/GLBAMLQSJ/p1582644081006900) should solve this deployment problem too. Sending the modules through the deploy task means that the association between that fragment and the host bundles will be fine. 

Thanks!

**Comment by istvansajtos** [comment]
Hi @balcsida ,

Do you think we can merge this? Even if the change turned out to be a simple source formatting change and doesn't fix the deployment issue as per my original intention, I think it is still worth to merge the change.

I changed the PR title and commit message to reflect what the change is about actually.

Thanks,
Pisti

**Comment by balcsida** [comment]
Hi @istvansajtos,

I assigned this to @CsabaTurcsan for review.

Kind regards,
Dávid

**Comment by balcsida** [comment]
Hi @istvansajtos,

With the latest GSearch connector update, the module resolve error is no longer present.
Thank you so much for your kind help and work on this matter! :)

**Comment by CsabaTurcsan** [comment]
Just started reviewing :)

**Comment by CsabaTurcsan** [comment]
Merged thx

**Pull request closed without merging**
